"""AIOS Kernel - Central infrastructure for agent intelligence.

Provides AgentManager, Heartbeat monitoring, and Scheduler for
recurring missions. Integrates with existing Orchestrator, EventBus,
TaskManager, and Monitor.
"""

import json
import os
import time
import threading
import logging
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone, timedelta
from enum import Enum
from typing import Any, Callable, Dict, List, Optional
from pathlib import Path
import uuid
import argparse
import sys


class AgentMode(Enum):
    """Operation mode for agents."""
    MANUAL = "manual"
    ASSISTED = "assisted"
    AUTONOMOUS = "autonomous"


class AgentHealth(Enum):
    """Agent health status."""
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    UNHEALTHY = "unhealthy"
    UNKNOWN = "unknown"


@dataclass
class AgentConfig:
    """Configuration for a registered agent."""
    name: str
    mode: AgentMode = AgentMode.ASSISTED
    capabilities: List[str] = field(default_factory=list)
    max_concurrent_tasks: int = 3
    heartbeat_interval_seconds: float = 30.0
    auto_suggest: bool = True
    domain: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "mode": self.mode.value,
            "capabilities": self.capabilities,
            "max_concurrent_tasks": self.max_concurrent_tasks,
            "heartbeat_interval_seconds": self.heartbeat_interval_seconds,
            "auto_suggest": self.auto_suggest,
            "domain": self.domain,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "AgentConfig":
        return cls(
            name=data["name"],
            mode=AgentMode(data.get("mode", "assisted")),
            capabilities=data.get("capabilities", []),
            max_concurrent_tasks=data.get("max_concurrent_tasks", 3),
            heartbeat_interval_seconds=data.get("heartbeat_interval_seconds", 30.0),
            auto_suggest=data.get("auto_suggest", True),
            domain=data.get("domain", ""),
            metadata=data.get("metadata", {}),
        )


@dataclass
class AgentHeartbeat:
    """Heartbeat data for an agent."""
    agent_name: str
    timestamp: str
    status: str
    active_tasks: int = 0
    latency_ms: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Suggestion:
    """A suggestion generated by an agent."""
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:12])
    agent_name: str = ""
    title: str = ""
    description: str = ""
    suggestion_type: str = "improvement"
    domain: str = ""
    priority: str = "medium"
    status: str = "pending"
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    reviewed_at: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class ScheduledMission:
    """A mission that runs on a schedule."""
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:12])
    name: str = ""
    description: str = ""
    agent_name: str = ""
    cron_expression: str = ""
    interval_seconds: Optional[float] = None
    enabled: bool = True
    last_run: Optional[str] = None
    next_run: Optional[str] = None
    run_count: int = 0
    task_template: Dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> dict:
        return asdict(self)


class HeartbeatMonitor:
    """Monitors agent health via periodic heartbeats."""

    def __init__(self):
        self._heartbeats: Dict[str, AgentHeartbeat] = {}
        self._lock = threading.Lock()
        self.logger = logging.getLogger("kernel.heartbeat")

    def record(self, agent_name: str, status: AgentHealth,
               active_tasks: int = 0, latency_ms: float = 0.0,
               metadata: Optional[Dict] = None):
        with self._lock:
            self._heartbeats[agent_name] = AgentHeartbeat(
                agent_name=agent_name,
                timestamp=datetime.now(timezone.utc).isoformat(),
                status=status.value,
                active_tasks=active_tasks,
                latency_ms=latency_ms,
                metadata=metadata or {},
            )

    def get(self, agent_name: str) -> Optional[AgentHeartbeat]:
        with self._lock:
            return self._heartbeats.get(agent_name)

    def get_all(self) -> Dict[str, AgentHeartbeat]:
        with self._lock:
            return dict(self._heartbeats)

    def get_stale(self, max_age_seconds: float = 60.0) -> List[str]:
        now = datetime.now(timezone.utc)
        stale = []
        with self._lock:
            for name, hb in self._heartbeats.items():
                try:
                    hb_time = datetime.fromisoformat(hb.timestamp)
                    if (now - hb_time).total_seconds() > max_age_seconds:
                        stale.append(name)
                except (ValueError, TypeError):
                    stale.append(name)
        return stale


class Scheduler:
    """Scheduler for recurring tasks and missions."""

    def __init__(self):
        self._missions: Dict[str, ScheduledMission] = {}
        self._running = False
        self._thread: Optional[threading.Thread] = None
        self._lock = threading.Lock()
        self.logger = logging.getLogger("kernel.scheduler")
        self._callbacks: Dict[str, Callable] = {}

    def add_mission(self, mission: ScheduledMission) -> str:
        with self._lock:
            self._missions[mission.id] = mission
        self.logger.info("Scheduled mission '%s' (id=%s)", mission.name, mission.id)
        return mission.id

    def remove_mission(self, mission_id: str) -> bool:
        with self._lock:
            if mission_id in self._missions:
                del self._missions[mission_id]
                return True
        return False

    def get_mission(self, mission_id: str) -> Optional[ScheduledMission]:
        with self._lock:
            return self._missions.get(mission_id)

    def get_all_missions(self) -> List[ScheduledMission]:
        with self._lock:
            return list(self._missions.values())

    def get_due_missions(self) -> List[ScheduledMission]:
        now = datetime.now(timezone.utc)
        due = []
        with self._lock:
            for mission in self._missions.values():
                if not mission.enabled:
                    continue
                if mission.next_run:
                    try:
                        next_time = datetime.fromisoformat(mission.next_run)
                        if next_time <= now:
                            due.append(mission)
                    except (ValueError, TypeError):
                        pass
                elif mission.interval_seconds:
                    if mission.last_run:
                        try:
                            last = datetime.fromisoformat(mission.last_run)
                            if (now - last).total_seconds() >= mission.interval_seconds:
                                due.append(mission)
                        except (ValueError, TypeError):
                            due.append(mission)
                    else:
                        due.append(mission)
        return due

    def mark_run(self, mission_id: str):
        with self._lock:
            mission = self._missions.get(mission_id)
            if mission:
                mission.last_run = datetime.now(timezone.utc).isoformat()
                mission.run_count += 1
                if mission.interval_seconds:
                    next_time = datetime.now(timezone.utc) + timedelta(seconds=mission.interval_seconds)
                    mission.next_run = next_time.isoformat()

    def register_callback(self, mission_id: str, callback: Callable):
        self._callbacks[mission_id] = callback

    def start(self):
        if self._running:
            return
        self._running = True
        self._thread = threading.Thread(target=self._loop, daemon=True, name="Scheduler")
        self._thread.start()
        self.logger.info("Scheduler started")

    def stop(self):
        self._running = False
        if self._thread:
            self._thread.join(timeout=5)
        self.logger.info("Scheduler stopped")

    def _loop(self):
        while self._running:
            try:
                due = self.get_due_missions()
                for mission in due:
                    self._execute_mission(mission)
                time.sleep(10)
            except Exception as e:
                self.logger.error("Scheduler loop error: %s", e)
                time.sleep(5)

    def _execute_mission(self, mission: ScheduledMission):
        self.logger.info("Executing scheduled mission: %s", mission.name)
        callback = self._callbacks.get(mission.id)
        if callback:
            try:
                callback(mission)
            except Exception as e:
                self.logger.error("Mission '%s' callback failed: %s", mission.name, e)
        self.mark_run(mission.id)


class AgentManager:
    """Manages dynamic agent registration, configuration, and mode."""

    def __init__(self, project_root: str):
        self.project_root = project_root
        self._agents: Dict[str, AgentConfig] = {}
        self._lock = threading.Lock()
        self.logger = logging.getLogger("kernel.agent_manager")
        self._config_dir = os.path.join(project_root, ".aios", "agents")
        os.makedirs(self._config_dir, exist_ok=True)
        self._load_configs()

    def _config_path(self, agent_name: str) -> str:
        return os.path.join(self._config_dir, f"{agent_name}.json")

    def _load_configs(self):
        if not os.path.isdir(self._config_dir):
            return
        for filename in os.listdir(self._config_dir):
            if filename.endswith(".json"):
                try:
                    with open(os.path.join(self._config_dir, filename)) as f:
                        data = json.load(f)
                    config = AgentConfig.from_dict(data)
                    self._agents[config.name] = config
                except Exception as e:
                    self.logger.warning("Failed to load config %s: %s", filename, e)

    def _save_config(self, config: AgentConfig):
        path = self._config_path(config.name)
        with open(path, "w") as f:
            json.dump(config.to_dict(), f, indent=2)

    def register(self, config: AgentConfig) -> AgentConfig:
        with self._lock:
            self._agents[config.name] = config
            self._save_config(config)
        self.logger.info("Agent '%s' registered (mode=%s)", config.name, config.mode.value)
        return config

    def unregister(self, agent_name: str) -> bool:
        with self._lock:
            if agent_name in self._agents:
                del self._agents[agent_name]
                path = self._config_path(agent_name)
                if os.path.exists(path):
                    os.remove(path)
                return True
        return False

    def get(self, agent_name: str) -> Optional[AgentConfig]:
        with self._lock:
            return self._agents.get(agent_name)

    def get_all(self) -> List[AgentConfig]:
        with self._lock:
            return list(self._agents.values())

    def set_mode(self, agent_name: str, mode: AgentMode) -> bool:
        config = self.get(agent_name)
        if config:
            with self._lock:
                config.mode = mode
                self._save_config(config)
            self.logger.info("Agent '%s' mode changed to %s", agent_name, mode.value)
            return True
        return False

    def get_by_mode(self, mode: AgentMode) -> List[AgentConfig]:
        with self._lock:
            return [c for c in self._agents.values() if c.mode == mode]

    def can_auto_suggest(self, agent_name: str) -> bool:
        config = self.get(agent_name)
        return config.auto_suggest if config else False

    def to_dict(self) -> Dict[str, Any]:
        with self._lock:
            return {name: config.to_dict() for name, config in self._agents.items()}


class AIOSKernel:
    """Main kernel that ties together all subsystems."""

    def __init__(self, project_root: str):
        self.project_root = project_root
        self.agent_manager = AgentManager(project_root)
        self.heartbeat = HeartbeatMonitor()
        self.scheduler = Scheduler()
        self.logger = logging.getLogger("kernel")

        self._orchestrator = None
        self._event_bus = None
        self._monitor = None

    def set_orchestrator(self, orchestrator):
        self._orchestrator = orchestrator
        self.logger.info("Orchestrator integrated")

    def set_event_bus(self, event_bus):
        self._event_bus = event_bus
        self.logger.info("EventBus integrated")

    def set_monitor(self, monitor):
        self._monitor = monitor
        self.logger.info("Monitor integrated")

    def start(self):
        self.scheduler.start()
        self.logger.info("AIOS Kernel started")

    def stop(self):
        self.scheduler.stop()
        self.logger.info("AIOS Kernel stopped")

    def get_status(self) -> Dict[str, Any]:
        agents_status = {}
        for config in self.agent_manager.get_all():
            hb = self.heartbeat.get(config.name)
            agents_status[config.name] = {
                "config": config.to_dict(),
                "heartbeat": asdict(hb) if hb else None,
            }

        return {
            "project_root": self.project_root,
            "agents_count": len(self.agent_manager.get_all()),
            "agents": agents_status,
            "scheduled_missions": len(self.scheduler.get_all_missions()),
            "due_missions": len(self.scheduler.get_due_missions()),
            "stale_agents": self.heartbeat.get_stale(),
        }


def create_default_kernel(project_root: str) -> AIOSKernel:
    """Create a kernel with default agent configurations."""
    kernel = AIOSKernel(project_root)

    default_agents = [
        AgentConfig(name="orchestrator", mode=AgentMode.AUTONOMOUS,
                   capabilities=["routing", "coordination"], domain="orchestration",
                   auto_suggest=False),
        AgentConfig(name="architect", mode=AgentMode.ASSISTED,
                   capabilities=["architecture", "design", "system", "pattern"],
                   domain="software architecture"),
        AgentConfig(name="engineer", mode=AgentMode.AUTONOMOUS,
                   capabilities=["coding", "implementation", "fix", "refactor"],
                   domain="software engineering"),
        AgentConfig(name="researcher", mode=AgentMode.ASSISTED,
                   capabilities=["analysis", "research", "data"],
                   domain="research and analysis"),
        AgentConfig(name="ai_specialist", mode=AgentMode.ASSISTED,
                   capabilities=["ai", "llm", "ml", "models"],
                   domain="artificial intelligence"),
        AgentConfig(name="automation", mode=AgentMode.AUTONOMOUS,
                   capabilities=["ci", "cd", "pipeline", "deploy", "monitoring"],
                   domain="automation and DevOps"),
        AgentConfig(name="database", mode=AgentMode.ASSISTED,
                   capabilities=["database", "sql", "schema", "queries"],
                   domain="database management"),
        AgentConfig(name="security", mode=AgentMode.ASSISTED,
                   capabilities=["security", "auth", "encryption", "vulnerabilities"],
                   domain="cybersecurity"),
        AgentConfig(name="browser", mode=AgentMode.AUTONOMOUS,
                   capabilities=["browser", "browse", "scrape", "web", "ocr",
                                  "screenshot", "download", "search", "extract_json"],
                   domain="web browsing and scraping",
                   metadata={"supports_playwright": True, "supports_ocr": True}),
    ]

    for config in default_agents:
        kernel.agent_manager.register(config)

    return kernel


def main():
    parser = argparse.ArgumentParser(description="AIOS Kernel")
    parser.add_argument("--project-root", default=os.getcwd())
    sub = parser.add_subparsers(dest="command")

    sub.add_parser("status", help="Show kernel status")

    p_agent = sub.add_parser("agent", help="Agent management")
    p_agent.add_argument("action", choices=["list", "register", "mode"])
    p_agent.add_argument("--name", help="Agent name")
    p_agent.add_argument("--mode", choices=["manual", "assisted", "autonomous"])

    p_sched = sub.add_parser("scheduler", help="Scheduler management")
    p_sched.add_argument("action", choices=["list", "due"])

    args = parser.parse_args()

    kernel = create_default_kernel(args.project_root)

    if args.command == "status":
        status = kernel.get_status()
        print(json.dumps(status, indent=2, default=str))
    elif args.command == "agent":
        if args.action == "list":
            for config in kernel.agent_manager.get_all():
                print(f"  {config.name:<16} mode={config.mode.value:<12} caps={config.capabilities}")
        elif args.action == "register" and args.name:
            config = AgentConfig(name=args.name, mode=AgentMode(args.mode or "assisted"))
            kernel.agent_manager.register(config)
            print(f"Registered agent: {args.name}")
        elif args.action == "mode" and args.name and args.mode:
            kernel.agent_manager.set_mode(args.name, AgentMode(args.mode))
            print(f"Agent {args.name} mode -> {args.mode}")
    elif args.command == "scheduler":
        if args.action == "list":
            for m in kernel.scheduler.get_all_missions():
                print(f"  {m.id[:8]}  {m.name:<20}  enabled={m.enabled}  runs={m.run_count}")
        elif args.action == "due":
            due = kernel.scheduler.get_due_missions()
            print(f"Due missions: {len(due)}")
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
